{% set version = "1.4.3" %}

package:
  name: django-ajax-selects
  version: {{ version }}

source:
  fn: django-ajax-selects-{{ version }}.tar.gz
  url: https://github.com/crucialfelix/django-ajax-selects/archive/{{ version }}.tar.gz
  sha256: 0e48486b4cc45c7d9ca96e21c501796dbc08b4aa079087c5ed525e8b797857a3

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - django

test:
  imports:
    - ajax_select

about:
  home: https://github.com/crucialfelix/django-ajax-selects/
  license: MIT
  license_file: LICENSE
  summary: 'Edit ForeignKey, ManyToManyField and CharField in Django Admin using jQuery UI AutoComplete.'

extra:
  recipe-maintainers:
    - ocefpaf
