# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "KdGCclAhZp5q+d5IZSKbHPleIr2P0+J7ofkps/U9WU6oAZ/xPUhDqlq//XI99sE4BKpMmTvWKioLuU+TIrmYWckGzsbxEjMbPAkLwQA7gfpInfQdYFXVM1ye8JdWPAf7Pl01Yjr1cfPZXpJVnDBHrANXDKjfHuQVBoz7OZqXDl4za+FkC0b1VDYRXs0ntrGLuMzVLVnthwqAQR+V8COKE6V+GXhnJEft7f+NsGG4g656eeHVf/OsC72yO17JbAwavvNPNFBedTg5sFhQ8ujT19P6C0RM7R9bxAEV+7wiC1zm0PmfZGhdRZ1/fT9wBUVEUTmyt/UF1cnW1+rqc9lv4tzAlMoRMgLT3rwJNSIz2+fR14u+UlqzQIpugm8OLWpPtxSab3VbLr3zmzwxWZHw3ROf++u+SuCbzh6q11HKn++JNbfpHAsNzr8oWoBXuuTLVrfF3DeW2w7eaxi15Q+9Hlv/LH63YPfJQR8qWpDm/oTREudfkeHWYzOBUrmdPKt2YO4keLrIugPVhHxxXvdw1urP1JbYoQT0qPuuJEyKx8v2mR6w0uX/fHeEKL8EsAOlDobg67nogB7tDB7+K1bDHE4lrFHe9XqFcp52fl5o8DmgMS1BuA0pAXUAVnRKldOeD0jyNbDk2xwuhoiT4DgGxChvlcTiUSqS3ej+GXWlrPs="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
