travis:
  secure:
    BINSTAR_TOKEN: sRONs4PGDajA/CkCxLgCsHs7I5pjzCtZcQPLt68ph4slUEAlPp8WbsuMEVms/zPH+a64w7w+lE9gVKAp/H9EaUJIDnTS7RCwpftEQD1gcEWhaMJJOyn/CW98ADjbLJtPk8KGZ8P8qntNgT8J5p6KSmhjughn30TqGlsXbRC0oiFHrZ7q83mLlJul/JiDfnQZbB10EwzySldLgVKk6caMbQG5gT2novUge6RYvKaUgnEYNJTYncjiH74T4q+MnHjLQwjaiTsZywxkos1Vtr3cn9zIZgYmT0Omv/OFN3CFUpgn/SGM3/PQWvjz7ge8X4lR4v9XzT6QXEzYfwTSV7Wr7R1aCZcvIQEuXJwYNv0f++m3yLnDRdOqqA0xVk0ppA1Dmr2roQ6tzT/cSaxM4Nm1OuWkw6wpo1AcmeKh7T+FYyh0qThKe6iX98nrfp3sP+FEaZX7FEKThNsUr226iX6advlNMIFhaOn2tDF81nKJ1PToGE0GekbR8ke3eM/D7HPxNGuIQqnSEWv06VW8qFUH58LvqAO3KrNp6lZ9KoCqrdQke09r9huXzWfRUBaaNt3XF7ODvLKegpIKz/w8FFIJQKH4PS3R1lbiRsIZRFiPjap4juSVC1tfpEXWD0a41qugaqOMy7Gf3a95mdQBJ6SmIKoJorFwPYMkZyzc4drWKOw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
