travis:
  secure:
    BINSTAR_TOKEN: KdGCclAhZp5q+d5IZSKbHPleIr2P0+J7ofkps/U9WU6oAZ/xPUhDqlq//XI99sE4BKpMmTvWKioLuU+TIrmYWckGzsbxEjMbPAkLwQA7gfpInfQdYFXVM1ye8JdWPAf7Pl01Yjr1cfPZXpJVnDBHrANXDKjfHuQVBoz7OZqXDl4za+FkC0b1VDYRXs0ntrGLuMzVLVnthwqAQR+V8COKE6V+GXhnJEft7f+NsGG4g656eeHVf/OsC72yO17JbAwavvNPNFBedTg5sFhQ8ujT19P6C0RM7R9bxAEV+7wiC1zm0PmfZGhdRZ1/fT9wBUVEUTmyt/UF1cnW1+rqc9lv4tzAlMoRMgLT3rwJNSIz2+fR14u+UlqzQIpugm8OLWpPtxSab3VbLr3zmzwxWZHw3ROf++u+SuCbzh6q11HKn++JNbfpHAsNzr8oWoBXuuTLVrfF3DeW2w7eaxi15Q+9Hlv/LH63YPfJQR8qWpDm/oTREudfkeHWYzOBUrmdPKt2YO4keLrIugPVhHxxXvdw1urP1JbYoQT0qPuuJEyKx8v2mR6w0uX/fHeEKL8EsAOlDobg67nogB7tDB7+K1bDHE4lrFHe9XqFcp52fl5o8DmgMS1BuA0pAXUAVnRKldOeD0jyNbDk2xwuhoiT4DgGxChvlcTiUSqS3ej+GXWlrPs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
